---

- name: 'set-host name'
  import_tasks: 'change_hn.yml'
  tags: [ 'set-host name' ]

- name: 'set-dns host'
  import_tasks: 'set-dns.yml'
  tags: ['set-dns host']

- name: 'CONFIG | config os_common'
  import_tasks: "config.yml"
  tags: ['os_common', 'os_common::config']

- name: 'COMMON_PACKAGES | install common packages'
  import_tasks: "common_packages.yml"
  tags: ['os_common', 'os_common::common_packages']

- name: 'open ports firewall'
  import_tasks: 'firewall.yml'
  tags: ['open ports firewall']
